all: server client

server: 
	g++ server.cpp --std=c++17 -I/Users/alexandrasorokovikova/boost_1_72_0 -pthread -o server
client:
	g++ client.cpp --std=c++17 -I/Users/alexandrasorokovikova/boost_1_72_0 -pthread -o client